version: '3'

services:
  db:
    image: postgres:10.1-alpine
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 selfies.asgi:application
    volumes:
      - .:/selfies
    ports:
      - "8000:8000"
    expose:
      - 8000
    links:
      - redis
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: python manage.py runworker channels -v2
    volumes:
     - .:/selfies
    links:
     - redis

volumes:
  postgres_data:
